version: "{build}"

platform: x64

branches:
  only:
    - master

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.9.2

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - 7z x go%GOVERSION%.windows-amd64.zip -y -oC:\ > NUL
  - go version
  - go env
  - mkdir c:\gopath

build_script:
  - go test -v .

test: off
deploy: off
